name:Portfolio

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubantu-latest

    steps:
    - name : Checkout Code
        user: actions/checkout@v2

    - name: Configure AWS Credentials
        user: actions/aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

    - name: Upload to S3
        run: aws s3 sync . s3://manishpatidar-portfolio  --delete     
